{% set name = "appnope" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 685db59cb6043c3c2e528adc0b3bce3a5f8d09bcf7492c6ea650d1b7421f3c49

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [not osx]
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - appnope
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/minrk/appnope
  summary: Disable App Nap on OS X >=10.9
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    appnope is a simple package for disabling App Nap on OS X >=10.9, which can be problematic.
  doc_url: https://github.com/minrk/appnope/blob/main/README.md
  dev_url: https://github.com/minrk/appnope

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
