{% set version = "0.1.2" %}

package:
  name: appnope
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/appnope/appnope-{{ version }}.tar.gz
  sha256: dd83cd4b5b460958838f6eb3000c660b1f9caf2a5b1de4264e941512f603258a

build:
  number: 1001
  skip: true  # [not osx]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - appnope

about:
  home: http://github.com/minrk/appnope
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Disable App Nap on OS X 10.9
  description: |
    appnope is a simple package for disabling App Nap on OS X 10.9, which can be problematic.
  doc_url: https://pypi.python.org/pypi/appnope/0.1.0
  doc_source_url: https://github.com/minrk/appnope/blob/master/README.md
  dev_url: https://github.com/minrk/appnope

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
