travis:
  secure:
    BINSTAR_TOKEN: gSViStvggoI7i+3Rid+KOhDMXAGdzBxLZWnpnsWG9afzzqAElRXKdnOpI597kuQQoA/AKfrfE/OU0syRn3RsLAKNZ5HKtCF1zl5k9Y7xsWC0WN1pr2KofH8oflK+u7PpoQk0rCvZjx6i+JNvkT40lTcFItZ3WeoBRAJdBXvOxxdx56ZAWGDcTrLiKbZlXxq84vbQe/my0MZAarngapIfWwxIB4RsT/6UEYp4BSw+MNkaWFp54763XFr9CoLA1hdLFzF0iFNv8Js2uhkiWFY9NRizqbgDIu5m9g3IQMNXs4bWuNQGaJVyYRXfB3ezx9UsxuIfaLo57KjJjRT/yMITo0YYObT3LPLpIe3Vdfd+GDMPKelu4X9Ynas49D5eC9i5C3O9D2xeC+0CLXJ/tHHiaoaCPHzz4SGlkCY/wqYwRXq6It2brM5BNO77HFKFucQQTK3BMSo3MOWaopFY7Q5sn5iMbuMgsw9r1LPrRmwmWVrjaBHM1zRI2wckGTqsn4OvaF8LXVkbPo39zNT7U9wQRS7FzCPqfeztEywma4ou/TD+zoEbWwAZfGRf/qXIem1j/kj7ZfWVlTfeh+0i5MGJF5dOSBdDi+lQPQ5XTl6+fkahkbHFQwRNA+2TqcpxCA3MB1BvTviEM5JQ3f/JLha6DzbgnBTKgrn2Sho4IuEKqJw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
